In [21]:
import pandas as pd
import os
import copy
import pandas_profiling

In [22]:
os.chdir('/Users/bblanchard006/Desktop/SMU/QTW/Week 7')
os.getcwd()

'/Users/bblanchard006/Desktop/SMU/QTW/Week 7'

In [23]:
df = pd.read_csv('car_data.txt', sep='\t')
df.columns.tolist()

['Auto', 'MPG', 'CYLINDERS', 'SIZE', 'HP', 'WEIGHT', 'ACCEL', 'ENG_TYPE']

In [24]:
df.head(5)

Auto   MPG  CYLINDERS   SIZE     HP  WEIGHT  ACCEL  \
0      Buick Estate Wagon  16.9        8.0  350.0  155.0   4.360   14.9   
1  Ford Country Sq. Wagon  15.5        8.0  351.0    NaN   4.054   14.3   
2      Chevy Malibu Wagon  19.2        8.0  267.0  125.0   3.605   15.0   
3     Chrys Lebaron Wagon  18.5        8.0  360.0  150.0   3.940   13.0   
4                Chevette  30.0        4.0   98.0   68.0   2.155   16.5   

   ENG_TYPE  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       0.0

In [25]:
df.Auto.unique()

array(['Buick Estate Wagon', 'Ford Country Sq. Wagon',
       'Chevy Malibu Wagon', 'Chrys Lebaron Wagon', 'Chevette',
       'Toyota Corona', 'Datsun 510', 'Dodge Omni', 'Audi 5000',
       'Volvo 240 GL', 'Saab 99 GLE', 'Peugeot 694 SL',
       'Buick Century Spec.', 'Mercury Zephyr', 'Dodge Aspen',
       'AMC Concord D/L', 'Chevy Caprice Classic', 'Ford LTD',
       'Mercury Grand Marquis', 'Dodge St Regis', 'Ford Mustang 4',
       'Ford Mustang Ghia', 'Mazda GLC', 'Dodge Colt', 'AMC Spirit',
       'VW Scirocco', 'Honda Accord', 'Buick Skylark', 'Chevy Citation',
       'Olds Omega', 'Pontiac Phoenix', 'Plymouth Horizon', 'Datsun 210',
       'Fiat Strada', 'VW Dasher', 'Datsun 810', 'BMW 320i', 'VW Rabbit'],
      dtype=object)

In [26]:
df['Auto'].unique()

array(['Buick Estate Wagon', 'Ford Country Sq. Wagon',
       'Chevy Malibu Wagon', 'Chrys Lebaron Wagon', 'Chevette',
       'Toyota Corona', 'Datsun 510', 'Dodge Omni', 'Audi 5000',
       'Volvo 240 GL', 'Saab 99 GLE', 'Peugeot 694 SL',
       'Buick Century Spec.', 'Mercury Zephyr', 'Dodge Aspen',
       'AMC Concord D/L', 'Chevy Caprice Classic', 'Ford LTD',
       'Mercury Grand Marquis', 'Dodge St Regis', 'Ford Mustang 4',
       'Ford Mustang Ghia', 'Mazda GLC', 'Dodge Colt', 'AMC Spirit',
       'VW Scirocco', 'Honda Accord', 'Buick Skylark', 'Chevy Citation',
       'Olds Omega', 'Pontiac Phoenix', 'Plymouth Horizon', 'Datsun 210',
       'Fiat Strada', 'VW Dasher', 'Datsun 810', 'BMW 320i', 'VW Rabbit'],
      dtype=object)

In [27]:
df.describe()

MPG  CYLINDERS        SIZE          HP     WEIGHT      ACCEL  \
count  38.000000  34.000000   35.000000   33.000000  32.000000  34.000000   
mean   24.760526   5.323529  180.885714  101.333333   2.905625  14.944118   
std     6.547314   1.609076   91.423955   27.118567   0.709191   1.589776   
min    15.500000   4.000000   85.000000   65.000000   1.915000  11.300000   
25%    18.525000   4.000000  105.000000   75.000000   2.282500  14.125000   
50%    24.250000   4.000000  151.000000   97.000000   2.747500  14.800000   
75%    30.375000   6.000000  244.500000  125.000000   3.458750  15.800000   
max    37.300000   8.000000  360.000000  155.000000   4.360000  19.200000   

        ENG_TYPE  
count  35.000000  
mean    0.285714  
std     0.458349  
min     0.000000  
25%     0.000000  
50%     0.000000  
75%     1.000000  
max     1.000000

In [28]:
profile = df.profile_report(title="Auto Dataset")
profile

### Q1: What is the maximum and minimum mpg for Ford and Chevy cars with more than 150 HP?

In [8]:
# One Options
car_makes = list(set(list(df.Auto)))
#car_makes = df.Auto.unique() # Alternatively

ford = [x for x in car_makes if 'Ford' in x]
chevy = [x for x in car_makes if 'Chev' in x]

ford_chevy_cars = ford + chevy

ford_chevy_cars

['Ford Country Sq. Wagon',
 'Ford Mustang 4',
 'Ford LTD',
 'Ford Mustang Ghia',
 'Chevette',
 'Chevy Citation',
 'Chevy Malibu Wagon',
 'Chevy Caprice Classic']

In [9]:
ford_chevy_df = df[df['Auto'].isin(ford_chevy_cars)]
ford_chevy_df

Auto   MPG  CYLINDERS   SIZE     HP  WEIGHT  ACCEL  \
1   Ford Country Sq. Wagon  15.5        8.0  351.0    NaN   4.054   14.3   
2       Chevy Malibu Wagon  19.2        8.0  267.0  125.0   3.605   15.0   
4                 Chevette  30.0        4.0   98.0   68.0   2.155   16.5   
16   Chevy Caprice Classic  17.0        NaN  305.0  130.0     NaN   15.4   
17                Ford LTD  17.6        8.0  302.0  129.0   3.725    NaN   
20          Ford Mustang 4  26.5        4.0  140.0    NaN   2.585   14.4   
21       Ford Mustang Ghia  21.9        6.0  171.0    NaN   2.910   16.6   
28          Chevy Citation  28.8        6.0  173.0  115.0   2.595   11.3   

    ENG_TYPE  
1        1.0  
2        1.0  
4        0.0  
16       1.0  
17       NaN  
20       0.0  
21       1.0  
28       1.0

In [10]:
# Another Option
ford_chevy_df = df[(df.Auto.str.contains('Ford') | df.Auto.str.contains('Chev'))]
ford_chevy_df

Auto   MPG  CYLINDERS   SIZE     HP  WEIGHT  ACCEL  \
1   Ford Country Sq. Wagon  15.5        8.0  351.0    NaN   4.054   14.3   
2       Chevy Malibu Wagon  19.2        8.0  267.0  125.0   3.605   15.0   
4                 Chevette  30.0        4.0   98.0   68.0   2.155   16.5   
16   Chevy Caprice Classic  17.0        NaN  305.0  130.0     NaN   15.4   
17                Ford LTD  17.6        8.0  302.0  129.0   3.725    NaN   
20          Ford Mustang 4  26.5        4.0  140.0    NaN   2.585   14.4   
21       Ford Mustang Ghia  21.9        6.0  171.0    NaN   2.910   16.6   
28          Chevy Citation  28.8        6.0  173.0  115.0   2.595   11.3   

    ENG_TYPE  
1        1.0  
2        1.0  
4        0.0  
16       1.0  
17       NaN  
20       0.0  
21       1.0  
28       1.0

In [11]:
ford_chevy_df['HP'].max()

130.0

In [12]:
ford_chevy_df.HP.max()

130.0

There are **no** records with an HP > 150 since the **max** in our dataframe is equal to 130.0

What about records with > 120 HP?

In [13]:
meet_hp_reqs = ford_chevy_df[ford_chevy_df.HP > 120] # 3 left
meet_hp_reqs

Auto   MPG  CYLINDERS   SIZE     HP  WEIGHT  ACCEL  \
2      Chevy Malibu Wagon  19.2        8.0  267.0  125.0   3.605   15.0   
16  Chevy Caprice Classic  17.0        NaN  305.0  130.0     NaN   15.4   
17               Ford LTD  17.6        8.0  302.0  129.0   3.725    NaN   

    ENG_TYPE  
2        1.0  
16       1.0  
17       NaN

In [14]:
min_ = meet_hp_reqs['MPG'].min() # 17
max_ = meet_hp_reqs['MPG'].max() # 19.2

print('The min = {} and the max = {}'.format(min_, max_))

The min = 17.0 and the max = 19.2


In [15]:
# and Another Option

min_ = df[(df.Auto.str.contains('Ford') | df.Auto.str.contains('Chev')) & (df.HP > 120)]['MPG'].min()
max_ = df[(df.Auto.str.contains('Ford') | df.Auto.str.contains('Chev')) & (df.HP > 120)]['MPG'].max()

print('The min = {} and the max = {}'.format(min_, max_))

The min = 17.0 and the max = 19.2


In [16]:
# and yet Another Option

min_ = df[(df.Auto.str.contains('(Ford|Chev)')) & (df.HP > 120)]['MPG'].min()
max_ = df[(df.Auto.str.contains('(Ford|Chev)')) & (df.HP > 120)]['MPG'].max()

print('The min = {} and the max = {}'.format(min_, max_))

The min = 17.0 and the max = 19.2


/anaconda3/lib/python3.6/site-packages/pandas/core/strings.py:1954: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)


### Q2: What is the median weight of cars in produced in 1970, 1972, and 1974?

In [17]:
# No data

### Q3: What are all the non-American cars with displacement >100 but not more than 200?

In [18]:
# No data

### Q4: What is the average MPG for each year for 6 cylinder cars? Do not include 1974. Or Fords.

In [19]:
# No yearly data; calculate in aggregate
new_df = copy.deepcopy(df)
new_df['Ford_Filter'] = new_df['Auto'].apply(lambda x: 1 if 'Ford' in x else 0)
new_df

Auto   MPG  CYLINDERS   SIZE     HP  WEIGHT  ACCEL  \
0       Buick Estate Wagon  16.9        8.0  350.0  155.0   4.360   14.9   
1   Ford Country Sq. Wagon  15.5        8.0  351.0    NaN   4.054   14.3   
2       Chevy Malibu Wagon  19.2        8.0  267.0  125.0   3.605   15.0   
3      Chrys Lebaron Wagon  18.5        8.0  360.0  150.0   3.940   13.0   
4                 Chevette  30.0        4.0   98.0   68.0   2.155   16.5   
5            Toyota Corona  27.5        4.0  134.0   95.0   2.560   14.2   
6               Datsun 510  27.2        4.0  119.0   97.0   2.300   14.7   
7               Dodge Omni  30.9        4.0  105.0   75.0   2.230   14.5   
8                Audi 5000  20.3        5.0  131.0    NaN   2.830   15.9   
9             Volvo 240 GL  17.0        6.0  163.0  125.0   3.140   13.6   
10             Saab 99 GLE  21.6        NaN  121.0  115.0   2.795   15.7   
11          Peugeot 694 SL  16.2        6.0    NaN  133.0   3.410   15.8   
12     Buick Century Spec.  20.6        NaN  231.0  105.0   3.380   15.8   
13          Mercury Zephyr  20.8        6.0  200.0   85.0     NaN   16.7   
14             Dodge Aspen  18.6        6.0  225.0  110.0   3.620   18.7   
15         AMC Concord D/L  18.1        NaN  258.0  120.0   3.410    NaN   
16   Chevy Caprice Classic  17.0        NaN  305.0  130.0     NaN   15.4   
17                Ford LTD  17.6        8.0  302.0  129.0   3.725    NaN   
18   Mercury Grand Marquis  16.5        8.0  351.0  138.0   3.955   13.2   
19          Dodge St Regis  18.2        8.0  318.0  135.0   3.830    NaN   
20          Ford Mustang 4  26.5        4.0  140.0    NaN   2.585   14.4   
21       Ford Mustang Ghia  21.9        6.0  171.0    NaN   2.910   16.6   
22               Mazda GLC  34.1        4.0   86.0   65.0     NaN   15.2   
23              Dodge Colt  35.1        4.0   98.0   80.0   1.915   14.4   
24              AMC Spirit  27.4        4.0  121.0    NaN   2.670   15.0   
25             VW Scirocco  31.5        4.0   89.0   71.0   1.990   14.9   
26            Honda Accord  29.5        4.0   98.0   68.0     NaN   16.6   
27           Buick Skylark  28.4        4.0  151.0   90.0   2.670   16.0   
28          Chevy Citation  28.8        6.0  173.0  115.0   2.595   11.3   
29              Olds Omega  26.8        6.0  173.0  115.0   2.700   12.9   
30         Pontiac Phoenix  33.5        4.0  151.0   90.0   2.556   13.2   
31        Plymouth Horizon  34.2        4.0  105.0   70.0   2.200   13.2   
32              Datsun 210  31.8        4.0   85.0   65.0   2.020   19.2   
33             Fiat Strada  37.3        4.0   91.0   69.0   2.130   14.7   
34               VW Dasher  30.5        4.0    NaN   78.0     NaN   14.1   
35              Datsun 810  22.0        6.0    NaN   97.0   2.815   14.5   
36                BMW 320i  21.5        4.0  121.0  110.0     NaN    NaN   
37               VW Rabbit  31.9        4.0   89.0   71.0   1.925   14.0   

    ENG_TYPE  Ford_Filter  
0        1.0            0  
1        1.0            1  
2        1.0            0  
3        1.0            0  
4        0.0            0  
5        0.0            0  
6        0.0            0  
7        NaN            0  
8        0.0            0  
9        0.0            0  
10       0.0            0  
11       0.0            0  
12       0.0            0  
13       0.0            0  
14       0.0            0  
15       0.0            0  
16       1.0            0  
17       NaN            1  
18       1.0            0  
19       1.0            0  
20       0.0            1  
21       1.0            1  
22       0.0            0  
23       0.0            0  
24       0.0            0  
25       0.0            0  
26       0.0            0  
27       0.0            0  
28       1.0            0  
29       1.0            0  
30       0.0            0  
31       0.0            0  
32       NaN            0  
33       0.0            0  
34       0.0            0  
35       0.0            0  
36       0.0         

In [20]:
mean_w_ford = new_df['MPG'].mean() # 24.76052631578947
mean_wo_ford = new_df[new_df['Ford_Filter'] == 0]['MPG'].mean() # 25.27647058823529

print('The average MPG including Ford is {}'.format(mean_w_ford))
print('The average MPG excluding Ford is {}'.format(mean_wo_ford))

The average MPG including Ford is 24.76052631578947
The average MPG excluding Ford is 25.27647058823529
